---
language: python
python: "3.9"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python3-pip

install:
  - python3 -m pip install molecule

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
