---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ pbis_packages_dependencies }}"
    state: present
  tags:
  - pbis_debian
  - pbis_dependencies_add

- name: Install gnupg2
  ansible.builtin.apt:
    name: "gnupg2"
    state: present
  when: pbis_install_gnupg2
  tags:
  - pbis_debian
  - pbis_gnupg2_add

- name: Check if keyring folder exist
  ansible.builtin.stat:
    path: "/usr/share/keyrings"
  register: keyring_folder
  tags:
  - pbis_debian
  - pbis_keyring_check

- name: Create keyring folder
  ansible.builtin.file:
    path: "/usr/share/keyrings"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not keyring_folder.stat.exists
  tags:
  - pbis_debian
  - pbis_keyring_add

# TODO: idempotence

- name: Get gpg repo key
  ansible.builtin.shell: "curl https://repo.pbis.beyondtrust.com/apt/RPM-GPG-KEY-pbis | gpg --dearmor"
  args:
    warn: no
  register: debian_repokey_file
  tags:
  - pbis_debian
  - pbis_repokey_get

- name: Add repo key 
  ansible.builtin.copy:
    content: "{{ debian_repokey_file.stdout }}"
    dest: "{{ pbis_keyring_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
  - pbis_debian
  - pbis_repokey_add

- name: Add pbis repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ pbis_keyring_file }}] {{ pbis_apt_repo }} {{ pbis_repo_args }}"
    state: present
  when: not pbis_enterprise_version
  tags:
  - pbis_debian
  - pbis_repo_add

- name: Install pbis
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ pbis_package }}"
    state: present
  tags:
  - pbis_debian
  - pbis_package_add