---
- name: Install gpg2
  ansible.builtin.apt:
    name: "gpg2"
    state: present
  when: install_gpg2
  tags:
  - pbis
  - pbis_debian
  - pbis_gpg2_add

- name: Install gpg2
  ansible.builtin.yum:
    name: "gpg2"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when: 
  - install_gpg2
  - ansible_distribution_major_version|int >= 6
  - ansible_distribution_major_version|int < 8
  tags:
  - pbis
  - pbis_redhat
  - pbis_gpg2_add

- name: Install gpg2
  ansible.builtin.dnf:
    name: "gpg2"
    state: present
  when: 
  - install_gpg2
  - ansible_distribution_major_version|int >= 8
  tags:
  - pbis
  - pbis_redhat
  - pbis_gpg2_add

- name: Check if keyring folder exist
  ansible.builtin.stat:
    path: "/usr/share/keyrings"
  register: keyring_folder
  tags:
  - pbis
  - pbis_debian
  - pbis_keyring_check

- name: Create keyring folder
  ansible.builtin.file:
    path: "/usr/share/keyrings"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: not keyring_folder.stat.exist
  tags:
  - pbis
  - pbis_debian
  - pbis_keyring_add

- name: Get gpg repo key
  ansible.builtin.shell: "curl https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor"
  register: debian_repokey_file
  tags:
  - pbis
  - pbis_debian
  - pbis_repokey_get

- name: Add repo key 
  ansible.builtin.copy:
    content: "{{ debian_repokey_file.stdout }}"
    dest: "{{ pbis_keyring_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
  - pbis
  - pbis_debian
  - pbis_repokey_add

- name: Add pbis repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ pbis_keyring_file }}] {{ pbis_apt_repo }} {{ pbis_repo_args }}"
    state: present
  when: not pbis_enterprise_version
  tags:
  - pbis
  - pbis_debian
  - pbis_repo_add

- name: Add pbis repository
  ansible.builtin.yum_repository:
    name: "{{ pbis_repo_name }}"
    baseurl: "{{ pbis_repo_baseurl }}"
    gpgkey: "{{ pbis_repo_gpgkey }}"
    gpgcheck: yes
    enabled : yes
  tags:
  - pbis
  - pbis_redhat
  - pbis_repo_add

- name: Install pbis
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ pbis_package }}"
    state: present
  tags:
  - pbis
  - pbis_debian
  - pbis_package_add

- name: Install gpg2
  ansible.builtin.yum:
    name: "{{ pbis_package }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python2
  when:
  - ansible_distribution_major_version|int >= 6
  - ansible_distribution_major_version|int < 8
  tags:
  - pbis
  - pbis_redhat
  - pbis_package_add

- name: Install gpg2
  ansible.builtin.dnf:
    name: "{{ pbis_package }}"
    state: present
  when:
  - ansible_distribution_major_version|int >= 8
  tags:
  - pbis
  - pbis_redhat
  - pbis_package_add
