---
- name: Domain Join
  shell: "{{ pbis_bin }}/domainjoin-cli join --ou {{pbis_join_ou}} {{pbis_domain}} {{pbis_join_user}} '{{pbis_join_pass}}'"
  tags:
    - pbis_join
    - pbis_join_add
    - molecule-idempotence-notest