---
- name: Include OS-specific variables.
  include_vars: "../vars/{{ ansible_os_family | lower }}.yml"
  tags:
  - pbis
  - pbis_vars

- name: PBIS Open for CentOS/RedHat
  import_tasks: redhat_install.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
  - pbis
  - pbis_redhat

- name: PBIS open for Debian/Ubuntu
  import_tasks: debian_install.yml
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
  - pbis
  - pbis_debian

# TODO: Configure pbis