name: Molecule

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - centos-7
          - debian-9
          - fedora-28
          - oraclelinux-7
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
